version: '3.9'
services:
    server:
        build:
            context: ./
            dockerfile: Dockerfile
            target: development
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - 5001:5001
        command: npm run serve:dev
